package io.archly.ai;
import java.time.*; import java.time.temporal.ChronoUnit; import java.util.Set; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
@Component class AiGenerationRateLimiter {
 private final AiRateLimitBucketRepository buckets; private final AiRateLimitLockRepository locks; private final boolean enabled; private final int daily,monthly; private final Set<String> models;
 AiGenerationRateLimiter(AiRateLimitBucketRepository buckets,AiRateLimitLockRepository locks,@Value("${archly.ai.enabled:true}") boolean enabled,@Value("${archly.ai.daily-user-requests:100}") int daily,@Value("${archly.ai.monthly-user-requests:1000}") int monthly,@Value("${archly.ai.allowed-models:gpt-4.1-mini}") Set<String> models){this.buckets=buckets;this.locks=locks;this.enabled=enabled;this.daily=daily;this.monthly=monthly;this.models=models;}
 @Transactional void check(String identity){check(identity,null);} @Transactional void check(String identity,String model){if(!enabled)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"AI generation is temporarily disabled.");if(model!=null&&!models.contains(model))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"This AI model is not allowed.");Instant now=Instant.now();ZonedDateTime utc=now.atZone(ZoneOffset.UTC);consume(identity+":minute:"+now.truncatedTo(ChronoUnit.MINUTES),10,"AI generation limit exceeded. Try again in a minute.");consume(identity+":day:"+utc.toLocalDate(),daily,"Daily AI generation limit reached.");consume(identity+":month:"+utc.getYear()+"-"+utc.getMonthValue(),monthly,"Monthly AI generation limit reached.");}
 @Transactional void reserve(String identity,String requestId){consume(identity+":request:"+requestId,1,"This AI request is already in progress or has been processed.",HttpStatus.CONFLICT);}
 private void consume(String key,int limit,String message){consume(key,limit,message,HttpStatus.TOO_MANY_REQUESTS);}
 private void consume(String key,int limit,String message,HttpStatus status){locks.acquire(Math.floorMod(key.hashCode(),64));AiRateLimitBucket value=buckets.lock(key).orElseGet(()->buckets.save(new AiRateLimitBucket(key)));if(value.increment()>limit)throw new ResponseStatusException(status,message);}
}
