package io.archly.ai;
import com.fasterxml.jackson.databind.JsonNode;import java.time.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.web.server.ResponseStatusException;
@Service public class AiUsageService {
 public record Summary(long monthlyEstimatedCostMicros,long monthlyBudgetMicros,long requests,long inputTokens,long outputTokens,long failures,boolean alert){}
 private final AiUsageRepository repo;private final long budget,userDailyBudget,userMonthlyBudget;private final double alertAt;
 AiUsageService(AiUsageRepository repo,@Value("${archly.ai.monthly-budget-micros:100000000}")long budget,@Value("${archly.ai.user-daily-budget-micros:5000000}")long userDailyBudget,@Value("${archly.ai.user-monthly-budget-micros:25000000}")long userMonthlyBudget,@Value("${archly.ai.budget-alert-percent:80}")double alertAt){this.repo=repo;this.budget=budget;this.userDailyBudget=userDailyBudget;this.userMonthlyBudget=userMonthlyBudget;this.alertAt=alertAt;}
 void ensureBudget(String user){if(repo.costSince(monthStart())>=budget)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"The administrator AI budget has been reached.");if(repo.userCostSince(user,dayStart())>=userDailyBudget)throw new ResponseStatusException(HttpStatus.TOO_MANY_REQUESTS,"Your daily AI cost limit has been reached.");if(repo.userCostSince(user,monthStart())>=userMonthlyBudget)throw new ResponseStatusException(HttpStatus.TOO_MANY_REQUESTS,"Your monthly AI cost limit has been reached.");}
 void ensureIdempotent(String requestId){if(repo.existsByRequestId(requestId))throw new ResponseStatusException(HttpStatus.CONFLICT,"This AI request was already processed.");}
 void record(String requestId,String user,String model,JsonNode response,String status){long input=response==null?0:response.path("usage").path("input_tokens").asLong();long output=response==null?0:response.path("usage").path("output_tokens").asLong();long cost=Math.round(input*0.15+output*0.60);repo.save(new AiUsageEvent(requestId,user,model,input,output,cost,status));}
 public Summary summary(){long cost=repo.costSince(monthStart());Object[] row=repo.totalsSince(monthStart());return new Summary(cost,budget,n(row[2]),n(row[0]),n(row[1]),n(row[3]),budget>0&&cost*100.0/budget>=alertAt);}private long n(Object value){return value==null?0:((Number)value).longValue();}private Instant dayStart(){return LocalDate.now(ZoneOffset.UTC).atStartOfDay(ZoneOffset.UTC).toInstant();}private Instant monthStart(){return YearMonth.now(ZoneOffset.UTC).atDay(1).atStartOfDay(ZoneOffset.UTC).toInstant();}
}
