import type { ArchitectureKind } from './canvasSizing'

export type ComponentDefinition = { kind: ArchitectureKind; label: string; description: string; iconId?: string; category?: string; keywords?: string }

export const componentDefinitions: ComponentDefinition[] = [
  { kind: 'service', label: 'Service / API', description: 'Backend or microservice', category: 'General' },
  { kind: 'service', label: 'Monolith', description: 'Single deployable application', iconId: 'monolith', category: 'General', keywords: 'monolithic application legacy system single tier all in one' },
  { kind: 'web', label: 'Web application', description: 'Browser-based application', category: 'General' },
  { kind: 'mobile', label: 'Mobile application', description: 'iOS or Android client', category: 'General' },
  { kind: 'service', label: 'Serverless Function', description: 'Event-driven stateless compute', iconId: 'serverless-function', category: 'General', keywords: 'lambda function faas cloud function' },
  { kind: 'service', label: 'Background Worker', description: 'Asynchronous processing service', iconId: 'background-worker', category: 'General', keywords: 'worker consumer processor daemon job' },
  { kind: 'service', label: 'Scheduled Job', description: 'Time-triggered workload', iconId: 'scheduled-job', category: 'General', keywords: 'cron scheduler batch timer' },
  { kind: 'cache', label: 'Cache', description: 'Fast temporary storage', category: 'General' },
  { kind: 'queue', label: 'Message Queue', description: 'Buffered asynchronous messaging', iconId: 'message-queue', category: 'General', keywords: 'queue broker fifo consumer producer' },
  { kind: 'external', label: 'External system', description: 'Third-party dependency', category: 'General' },
  { kind: 'actor', label: 'User / Actor', description: 'Person or system actor', category: 'General' },
  { kind: 'container', label: 'Boundary', description: 'System, network, or provider boundary', category: 'General' },
  { kind: 'note', label: 'Note', description: 'Diagram annotation', category: 'General' },
  { kind: 'text', label: 'Text', description: 'Standalone label', category: 'General' },
  { kind: 'custom', label: 'Custom Component', description: 'User-defined architecture element', category: 'General', keywords: 'custom generic user defined architecture block' },
  { kind: 'service', label: 'AWS Lambda', description: 'Serverless function', iconId: 'aws-lambda', category: 'AWS', keywords: 'amazon function faas' },
  { kind: 'database', label: 'Amazon DynamoDB', description: 'Managed NoSQL database', iconId: 'aws-dynamodb', category: 'AWS', keywords: 'aws dynamo nosql key value document table' },
  { kind: 'service', label: 'Amazon ECS', description: 'Elastic Container Service', iconId: 'aws-ecs', category: 'AWS', keywords: 'aws elastic container service cluster task' },
  { kind: 'service', label: 'AWS Fargate', description: 'Serverless container compute', iconId: 'aws-fargate', category: 'AWS', keywords: 'aws ecs serverless container task compute' },
  { kind: 'service', label: 'Amazon EC2', description: 'Elastic virtual machines', iconId: 'aws-ec2', category: 'AWS', keywords: 'aws compute instance virtual machine vm' },
  { kind: 'storage', label: 'Amazon S3', description: 'Managed object storage', iconId: 'aws-s3', category: 'AWS', keywords: 'aws bucket blob object file storage' },
  { kind: 'database', label: 'Amazon RDS', description: 'Managed relational database', iconId: 'aws-rds', category: 'AWS', keywords: 'aws sql mysql postgres aurora relational' },
  { kind: 'queue', label: 'Amazon SQS', description: 'Managed message queue', iconId: 'aws-sqs', category: 'AWS', keywords: 'aws messaging queue fifo' },
  { kind: 'queue', label: 'Amazon SNS', description: 'Managed pub/sub notifications', iconId: 'aws-sns', category: 'AWS', keywords: 'aws notification topic pubsub messaging' },
  { kind: 'service', label: 'Amazon API Gateway', description: 'Managed API entry point', iconId: 'aws-api-gateway', category: 'AWS', keywords: 'aws rest http websocket ingress endpoint' },
  { kind: 'external', label: 'Amazon CloudFront', description: 'Global content delivery network', iconId: 'aws-cloudfront', category: 'AWS', keywords: 'aws cdn edge cache distribution' },
  { kind: 'service', label: 'Amazon EKS', description: 'Managed Kubernetes service', iconId: 'aws-eks', category: 'AWS', keywords: 'aws elastic kubernetes k8s cluster' },
  { kind: 'service', label: 'Azure Function', description: 'Serverless function', iconId: 'azure-function', category: 'Azure', keywords: 'microsoft function faas' },
  { kind: 'service', label: 'Azure App Service', description: 'Managed web application platform', iconId: 'azure-app-service', category: 'Azure', keywords: 'microsoft web api paas application' },
  { kind: 'service', label: 'Azure Virtual Machine', description: 'Cloud virtual machine', iconId: 'azure-vm', category: 'Azure', keywords: 'microsoft compute instance vm' },
  { kind: 'storage', label: 'Azure Storage Account', description: 'Blob, file, queue, and table storage', iconId: 'azure-storage', category: 'Azure', keywords: 'microsoft blob file object storage' },
  { kind: 'database', label: 'Azure Cosmos DB', description: 'Globally distributed NoSQL database', iconId: 'azure-cosmos-db', category: 'Azure', keywords: 'microsoft nosql document database' },
  { kind: 'queue', label: 'Azure Service Bus', description: 'Enterprise message broker', iconId: 'azure-service-bus', category: 'Azure', keywords: 'microsoft queue topic messaging broker' },
  { kind: 'service', label: 'Azure Kubernetes Service', description: 'Managed Kubernetes service', iconId: 'azure-aks', category: 'Azure', keywords: 'microsoft aks k8s cluster container' },
  { kind: 'storage', label: 'Azure Key Vault', description: 'Managed secrets and keys', iconId: 'azure-key-vault', category: 'Azure', keywords: 'microsoft secret certificate security key' },
  { kind: 'service', label: 'Azure Application Gateway', description: 'Layer 7 load balancer', iconId: 'azure-application-gateway', category: 'Azure', keywords: 'microsoft ingress waf load balancer networking' },
  { kind: 'queue', label: 'GCP Pub/Sub', description: 'Managed messaging', iconId: 'gcp-pubsub', category: 'Google Cloud', keywords: 'google cloud events topic subscription' },
  { kind: 'service', label: 'Compute Engine', description: 'Cloud virtual machines', iconId: 'gcp-compute-engine', category: 'Google Cloud', keywords: 'google cloud compute instance vm' },
  { kind: 'service', label: 'Cloud Run', description: 'Serverless container platform', iconId: 'gcp-cloud-run', category: 'Google Cloud', keywords: 'google cloud serverless container service' },
  { kind: 'service', label: 'Cloud Functions', description: 'Serverless functions', iconId: 'gcp-cloud-functions', category: 'Google Cloud', keywords: 'google cloud function faas' },
  { kind: 'storage', label: 'Cloud Storage', description: 'Managed object storage', iconId: 'gcp-cloud-storage', category: 'Google Cloud', keywords: 'google cloud bucket blob object file' },
  { kind: 'database', label: 'Cloud SQL', description: 'Managed relational database', iconId: 'gcp-cloud-sql', category: 'Google Cloud', keywords: 'google cloud mysql postgres relational database' },
  { kind: 'database', label: 'Firestore', description: 'Managed document database', iconId: 'gcp-firestore', category: 'Google Cloud', keywords: 'google cloud firebase nosql document database' },
  { kind: 'service', label: 'Google Kubernetes Engine', description: 'Managed Kubernetes service', iconId: 'gcp-gke', category: 'Google Cloud', keywords: 'google cloud gke k8s cluster container' },
  { kind: 'database', label: 'BigQuery', description: 'Serverless data warehouse', iconId: 'gcp-bigquery', category: 'Google Cloud', keywords: 'google cloud analytics warehouse sql data' },
  { kind: 'service', label: 'Cloud Load Balancing', description: 'Global managed load balancing', iconId: 'gcp-load-balancing', category: 'Google Cloud', keywords: 'google cloud networking traffic ingress balancer' },
  { kind: 'service', label: 'Container', description: 'Packaged application workload', iconId: 'container', category: 'General', keywords: 'runtime image pod workload' },
  { kind: 'service', label: 'Kubernetes Cluster', description: 'Container orchestration', iconId: 'kubernetes', category: 'General', keywords: 'k8s cluster pod deployment kubernetes' },
  { kind: 'queue', label: 'Kafka', description: 'Distributed event streaming', iconId: 'kafka', category: 'General', keywords: 'apache event stream broker' },
  { kind: 'cache', label: 'Redis', description: 'In-memory data store', iconId: 'redis', category: 'General', keywords: 'cache key value' },
  { kind: 'database', label: 'PostgreSQL', description: 'Relational database', iconId: 'postgresql', category: 'General', keywords: 'postgres sql rdbms' },
  { kind: 'service', label: 'Docker', description: 'Application container', iconId: 'docker', category: 'General', keywords: 'container image runtime' },
  { kind: 'service', label: 'API Gateway', description: 'API entry point and routing', iconId: 'api-gateway', category: 'General', keywords: 'ingress endpoint routing rest' },
  { kind: 'service', label: 'Load Balancer', description: 'Distribute network traffic', iconId: 'load-balancer', category: 'General', keywords: 'alb elb traffic proxy' },
  { kind: 'service', label: 'Reverse Proxy', description: 'Proxy and route inbound traffic', iconId: 'reverse-proxy', category: 'General', keywords: 'nginx envoy ingress routing proxy' },
  { kind: 'external', label: 'DNS', description: 'Domain name resolution', iconId: 'dns', category: 'General', keywords: 'domain nameserver route53 lookup' },
  { kind: 'container', label: 'Network / VPC', description: 'Isolated network boundary', iconId: 'network-vpc', category: 'General', keywords: 'virtual private cloud subnet network boundary' },
  { kind: 'service', label: 'Firewall / WAF', description: 'Filter and protect network traffic', iconId: 'firewall-waf', category: 'General', keywords: 'security rules web application firewall acl' },
  { kind: 'storage', label: 'Object Storage', description: 'Blob and object storage', iconId: 'object-storage', category: 'General', keywords: 's3 bucket blob files' },
  { kind: 'external', label: 'CDN', description: 'Content delivery network', iconId: 'cdn', category: 'General', keywords: 'cloudfront edge cache content delivery' },
  { kind: 'database', label: 'SQL Database', description: 'Relational data store', iconId: 'sql-database', category: 'General', keywords: 'rdbms relational mysql' },
  { kind: 'database', label: 'NoSQL Database', description: 'Document or key-value store', iconId: 'nosql-database', category: 'General', keywords: 'dynamodb mongodb document key value' },
  { kind: 'database', label: 'Search Engine', description: 'Indexed full-text search', iconId: 'search-engine', category: 'General', keywords: 'elasticsearch opensearch index query' },
  { kind: 'database', label: 'Data Warehouse', description: 'Analytical data platform', iconId: 'data-warehouse', category: 'General', keywords: 'analytics olap reporting bigquery redshift' },
  { kind: 'queue', label: 'Event Bus', description: 'Route domain events', iconId: 'event-bus', category: 'General', keywords: 'eventbridge topic pubsub events' },
  { kind: 'queue', label: 'Event Stream', description: 'Ordered stream of events', iconId: 'event-stream', category: 'General', keywords: 'streaming log partition topic events' },
  { kind: 'storage', label: 'Secrets Manager', description: 'Credentials and secret storage', iconId: 'secrets-manager', category: 'General', keywords: 'vault key credentials password' },
  { kind: 'external', label: 'Monitoring', description: 'Metrics, logs, and alerts', iconId: 'monitoring', category: 'Operations - CD/CI', keywords: 'observability telemetry logs metrics alerts' },
  { kind: 'external', label: 'Logging', description: 'Centralized application logs', iconId: 'logging', category: 'Operations - CD/CI', keywords: 'log aggregation observability audit events' },
  { kind: 'service', label: 'CI/CD Pipeline', description: 'Automated build and deployment', iconId: 'ci-cd-pipeline', category: 'Operations - CD/CI', keywords: 'continuous integration delivery deployment build release' },
  { kind: 'external', label: 'Git Repository', description: 'Source code repository', iconId: 'git-repository', category: 'Operations - CD/CI', keywords: 'git source control github gitlab bitbucket scm' },
  { kind: 'service', label: 'Jenkins', description: 'Build and delivery automation', iconId: 'jenkins', category: 'Operations - CD/CI', keywords: 'ci cd pipeline build automation devops' },
  { kind: 'service', label: 'GitHub Actions', description: 'Repository-native workflow automation', iconId: 'github-actions', category: 'Operations - CD/CI', keywords: 'ci cd workflow github runner pipeline' },
  { kind: 'service', label: 'GitLab CI', description: 'Integrated CI/CD pipelines', iconId: 'gitlab-ci', category: 'Operations - CD/CI', keywords: 'gitlab runner pipeline continuous integration delivery' },
  { kind: 'service', label: 'Argo CD', description: 'GitOps continuous delivery', iconId: 'argo-cd', category: 'Operations - CD/CI', keywords: 'argocd gitops kubernetes deployment delivery' },
  { kind: 'service', label: 'Terraform', description: 'Infrastructure as code', iconId: 'terraform', category: 'Operations - CD/CI', keywords: 'hashicorp iac provisioning cloud infrastructure' },
  { kind: 'service', label: 'Ansible', description: 'Configuration and deployment automation', iconId: 'ansible', category: 'Operations - CD/CI', keywords: 'automation configuration management playbook devops' },
  { kind: 'service', label: 'Helm', description: 'Kubernetes package management', iconId: 'helm', category: 'Operations - CD/CI', keywords: 'kubernetes chart release deployment package' },
  { kind: 'external', label: 'Prometheus', description: 'Metrics collection and alerting', iconId: 'prometheus', category: 'Operations - CD/CI', keywords: 'sre monitoring metrics alert observability' },
  { kind: 'external', label: 'Grafana', description: 'Operational dashboards and visualization', iconId: 'grafana', category: 'Operations - CD/CI', keywords: 'sre dashboard metrics logs observability' },
  { kind: 'external', label: 'OpenTelemetry', description: 'Vendor-neutral telemetry collection', iconId: 'opentelemetry', category: 'Operations - CD/CI', keywords: 'otel traces metrics logs observability sre' },
  { kind: 'external', label: 'PagerDuty', description: 'Incident response and on-call management', iconId: 'pagerduty', category: 'Operations - CD/CI', keywords: 'sre incident alert oncall operations' },
  { kind: 'service', label: 'AI Agent', description: 'Autonomous tool-using AI workflow', iconId: 'ai-agent', category: 'AI / ML', keywords: 'agent assistant autonomous tool calling' },
  { kind: 'service', label: 'Foundation Model / LLM', description: 'Large language or foundation model', iconId: 'foundation-model', category: 'AI / ML', keywords: 'llm generative model transformer' },
  { kind: 'service', label: 'Embedding Model', description: 'Convert content into vectors', iconId: 'embedding-model', category: 'AI / ML', keywords: 'embedding vector representation semantic' },
  { kind: 'service', label: 'Multimodal Model', description: 'Text, image, audio, or video model', iconId: 'multimodal-model', category: 'AI / ML', keywords: 'vision audio image video vlm' },
  { kind: 'text', label: 'Prompt Template', description: 'Versioned model instructions', iconId: 'prompt-template', category: 'AI / ML', keywords: 'prompt system instruction template' },
  { kind: 'service', label: 'RAG Pipeline', description: 'Retrieval-augmented generation flow', iconId: 'rag-pipeline', category: 'AI / ML', keywords: 'rag retrieve augment context generation' },
  { kind: 'service', label: 'Retriever', description: 'Fetch relevant knowledge', iconId: 'retriever', category: 'AI / ML', keywords: 'search retrieval context semantic' },
  { kind: 'database', label: 'Vector Database', description: 'Store and search embeddings', iconId: 'vector-database', category: 'AI / ML', keywords: 'vector store similarity semantic index' },
  { kind: 'service', label: 'AI Tool / Function', description: 'Capability callable by an agent', iconId: 'ai-tool', category: 'AI / ML', keywords: 'function tool calling action plugin' },
  { kind: 'service', label: 'MCP Server', description: 'Model Context Protocol tool server', iconId: 'mcp-server', category: 'AI / ML', keywords: 'mcp context protocol tools resources' },
  { kind: 'service', label: 'Model Gateway', description: 'Route requests across models', iconId: 'model-gateway', category: 'AI / ML', keywords: 'proxy router fallback provider llm gateway' },
  { kind: 'service', label: 'Inference Endpoint', description: 'Production model-serving endpoint', iconId: 'inference-endpoint', category: 'AI / ML', keywords: 'serve deploy prediction api model' },
  { kind: 'storage', label: 'Model Registry', description: 'Version and govern model artifacts', iconId: 'model-registry', category: 'AI / ML', keywords: 'model artifact version registry mlops' },
  { kind: 'service', label: 'AI Guardrail', description: 'Validate model input and output', iconId: 'ai-guardrail', category: 'AI / ML', keywords: 'safety moderation policy validation' },
  { kind: 'external', label: 'Evaluation Service', description: 'Test model and agent quality', iconId: 'evaluation-service', category: 'AI / ML', keywords: 'eval benchmark quality test score' },
  { kind: 'actor', label: 'Human Approval', description: 'Human-in-the-loop decision', iconId: 'human-approval', category: 'AI / ML', keywords: 'hitl review approve oversight' },
  { kind: 'service', label: 'GPU Compute', description: 'Accelerated AI compute', iconId: 'gpu-compute', category: 'AI / ML', keywords: 'gpu cuda accelerator training inference' },
  { kind: 'external', label: 'OpenAI', description: 'Foundation models and AI APIs', iconId: 'openai', category: 'AI / ML', keywords: 'gpt responses embeddings realtime' },
  { kind: 'external', label: 'Anthropic Claude', description: 'Claude models and API', iconId: 'anthropic-claude', category: 'AI / ML', keywords: 'anthropic claude llm model api' },
  { kind: 'external', label: 'Google Gemini', description: 'Google multimodal model platform', iconId: 'google-gemini', category: 'AI / ML', keywords: 'google gemini ai model api' },
  { kind: 'external', label: 'Meta Llama', description: 'Open foundation model family', iconId: 'meta-llama', category: 'AI / ML', keywords: 'meta llama open model' },
  { kind: 'external', label: 'Mistral AI', description: 'Mistral model platform', iconId: 'mistral-ai', category: 'AI / ML', keywords: 'mistral mixtral model api' },
  { kind: 'external', label: 'Cohere', description: 'Enterprise language model platform', iconId: 'cohere', category: 'AI / ML', keywords: 'command rerank embed model api' },
  { kind: 'external', label: 'Hugging Face', description: 'Model hub and inference platform', iconId: 'hugging-face', category: 'AI / ML', keywords: 'transformers hub models datasets inference' },
  { kind: 'service', label: 'LangChain', description: 'LLM application framework', iconId: 'langchain', category: 'AI / ML', keywords: 'chain agent rag framework' },
  { kind: 'service', label: 'LangGraph', description: 'Stateful agent orchestration', iconId: 'langgraph', category: 'AI / ML', keywords: 'agent graph workflow durable orchestration' },
  { kind: 'service', label: 'LlamaIndex', description: 'Data framework for LLM applications', iconId: 'llamaindex', category: 'AI / ML', keywords: 'rag retrieval data framework index' },
  { kind: 'service', label: 'Semantic Kernel', description: 'Microsoft agent and AI SDK', iconId: 'semantic-kernel', category: 'AI / ML', keywords: 'microsoft agent orchestration sdk plugins' },
  { kind: 'service', label: 'CrewAI', description: 'Multi-agent orchestration framework', iconId: 'crewai', category: 'AI / ML', keywords: 'crew multi agent workflow framework' },
  { kind: 'database', label: 'Pinecone', description: 'Managed vector database', iconId: 'pinecone', category: 'AI / ML', keywords: 'vector database similarity search' },
  { kind: 'database', label: 'Weaviate', description: 'AI-native vector database', iconId: 'weaviate', category: 'AI / ML', keywords: 'vector database semantic search' },
  { kind: 'database', label: 'Milvus', description: 'Open-source vector database', iconId: 'milvus', category: 'AI / ML', keywords: 'vector database similarity search' },
  { kind: 'database', label: 'Qdrant', description: 'Vector search engine', iconId: 'qdrant', category: 'AI / ML', keywords: 'vector database similarity search' },
  { kind: 'database', label: 'Chroma', description: 'Embedding database for AI', iconId: 'chroma', category: 'AI / ML', keywords: 'chromadb vector embeddings database' },
  { kind: 'database', label: 'pgvector', description: 'PostgreSQL vector extension', iconId: 'pgvector', category: 'AI / ML', keywords: 'postgres vector similarity extension' },
  { kind: 'service', label: 'vLLM', description: 'High-throughput model serving', iconId: 'vllm', category: 'AI / ML', keywords: 'inference serving engine llm' },
  { kind: 'service', label: 'Ollama', description: 'Local model runtime', iconId: 'ollama', category: 'AI / ML', keywords: 'local model inference runtime' },
  { kind: 'service', label: 'Hugging Face Inference', description: 'Managed model inference', iconId: 'hf-inference', category: 'AI / ML', keywords: 'hugging face endpoint serving model' },
  { kind: 'service', label: 'NVIDIA NIM', description: 'Optimized inference microservice', iconId: 'nvidia-nim', category: 'AI / ML', keywords: 'nvidia inference microservice gpu' },
  { kind: 'service', label: 'NVIDIA Triton', description: 'Production inference server', iconId: 'nvidia-triton', category: 'AI / ML', keywords: 'nvidia triton model serving inference' },
  { kind: 'service', label: 'Text Generation Inference', description: 'Hugging Face LLM serving engine', iconId: 'tgi', category: 'AI / ML', keywords: 'hugging face tgi model server' },
  { kind: 'service', label: 'SGLang', description: 'High-performance model runtime', iconId: 'sglang', category: 'AI / ML', keywords: 'inference serving structured generation' },
  { kind: 'external', label: 'LangSmith', description: 'Agent tracing and evaluation', iconId: 'langsmith', category: 'AI / ML', keywords: 'langchain trace eval observability prompt' },
  { kind: 'external', label: 'MLflow', description: 'ML lifecycle and model tracking', iconId: 'mlflow', category: 'AI / ML', keywords: 'mlops experiment registry tracking' },
  { kind: 'external', label: 'Weights & Biases', description: 'ML experiments and observability', iconId: 'weights-biases', category: 'AI / ML', keywords: 'wandb experiment tracking evaluation' },
  { kind: 'external', label: 'Arize Phoenix', description: 'Open-source AI observability', iconId: 'arize-phoenix', category: 'AI / ML', keywords: 'trace eval observability llm' },
  { kind: 'external', label: 'Helicone', description: 'LLM observability gateway', iconId: 'helicone', category: 'AI / ML', keywords: 'llm logs proxy metrics observability' },
  { kind: 'external', label: 'Promptfoo', description: 'Prompt testing and red teaming', iconId: 'promptfoo', category: 'AI / ML', keywords: 'eval test prompt security red team' },
  { kind: 'service', label: 'Amazon Bedrock', description: 'AWS foundation model platform', iconId: 'aws-bedrock', category: 'AWS', keywords: 'aws generative ai agents foundation model' },
  { kind: 'service', label: 'Amazon SageMaker AI', description: 'AWS machine learning platform', iconId: 'aws-sagemaker', category: 'AWS', keywords: 'aws ml training endpoint model' },
  { kind: 'service', label: 'Azure OpenAI', description: 'OpenAI models hosted on Azure', iconId: 'azure-openai', category: 'Azure', keywords: 'microsoft ai gpt model endpoint' },
  { kind: 'service', label: 'Azure AI Foundry', description: 'Azure AI application platform', iconId: 'azure-ai-foundry', category: 'Azure', keywords: 'microsoft ai studio model agent' },
  { kind: 'service', label: 'Google Vertex AI', description: 'Google Cloud AI platform', iconId: 'gcp-vertex-ai', category: 'Google Cloud', keywords: 'gcp vertex machine learning model endpoint' },
  { kind: 'service', label: 'Google Gemini API', description: 'Gemini models on Google Cloud', iconId: 'gcp-gemini-api', category: 'Google Cloud', keywords: 'gcp google gemini generative ai model api' },
  { kind: 'external', label: 'Identity Provider', description: 'Authentication and identity', iconId: 'identity-provider', category: 'General', keywords: 'idp auth oauth oidc sso' },
  { kind: 'external', label: 'Email', description: 'Email delivery and communication', iconId: 'email', category: 'General', keywords: 'smtp mail message ses sendgrid' },
  { kind: 'external', label: 'Notification', description: 'Application alerts and notifications', iconId: 'notification', category: 'General', keywords: 'alert push notify bell message' },
  { kind: 'external', label: 'Slack', description: 'Team messaging and automation', iconId: 'slack', category: 'General', keywords: 'chat collaboration webhook notification workspace' },
  { kind: 'external', label: 'Microsoft Teams', description: 'Team collaboration and communication', iconId: 'microsoft-teams', category: 'General', keywords: 'teams microsoft chat meeting webhook notification' },
  { kind: 'external', label: 'SMS', description: 'Text message delivery', iconId: 'sms', category: 'General', keywords: 'mobile phone text message notification' },
  { kind: 'external', label: 'Push Notification', description: 'Mobile and browser push delivery', iconId: 'push-notification', category: 'General', keywords: 'alert device browser mobile notification' },
  { kind: 'external', label: 'Webhook', description: 'HTTP event callback', iconId: 'webhook', category: 'General', keywords: 'http callback integration event api' },
  { kind: 'external', label: 'Microsoft Outlook', description: 'Microsoft email and calendar', iconId: 'microsoft-outlook', category: 'General', keywords: 'outlook office 365 email mail calendar' },
  { kind: 'external', label: 'Gmail', description: 'Google email service', iconId: 'gmail', category: 'General', keywords: 'google workspace email mail' },
  { kind: 'external', label: 'Twilio', description: 'Programmable communications platform', iconId: 'twilio', category: 'General', keywords: 'sms voice phone messaging api' },
  { kind: 'external', label: 'SendGrid', description: 'Transactional email delivery', iconId: 'sendgrid', category: 'General', keywords: 'email smtp transactional delivery twilio' },
  { kind: 'external', label: 'Discord', description: 'Community messaging platform', iconId: 'discord', category: 'General', keywords: 'chat community webhook notification bot' },
]
